### ISSUE TITLE
Question wording to be included in the .hyper and not the field/ column name 

### ISSUE THREAD

**Issue by akahure** [onaio/duva#18]
The resultant .hyper brings the dataset by Field/column “name” which is most of the time is just a question code (e.g: SB01). For better convenience, and even to leverage Tableau “Ask Data” tool, columns (data points) need to be in full question wording (the label in ODK) rather than question name. (adding an option that allows choosing “names” or “labels” will be super useful.)

**Comment by IbrahimHd** [comment]
Hi @akahure,

I kindly ask you to this request a high priority as it's really needed for the reason mentioned above as well as for allowing us to keep using the already built Tableau Dashboards, which are quite a lot. At the moment, we can't put the developed connect in use unless this option is implemented.
Pushing this foward to get it implemented the soonest is highly appreciated.

Many thanks in advance.
Ibrahim
